/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as MpesaCallbackRouteImport } from './routes/mpesa.callback'
import { Route as C2bValidationRouteImport } from './routes/c2b.validation'
import { Route as C2bConfirmationRouteImport } from './routes/c2b.confirmation'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppSmsAutomationRouteImport } from './routes/_app.sms-automation'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppDebugRouteImport } from './routes/_app.debug'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api.mpesa.callback'
import { Route as ApiDebugTestPaymentRouteImport } from './routes/api.debug.test-payment'
import { Route as ApiDebugSimulateC2bRouteImport } from './routes/api.debug.simulate-c2b'
import { Route as ApiDebugHealthRouteImport } from './routes/api.debug.health'
import { Route as ApiDebugCallbacksRouteImport } from './routes/api.debug.callbacks'
import { Route as ApiPaymentsC2bValidationRouteImport } from './routes/api.payments.c2b.validation'
import { Route as ApiPaymentsC2bStatusRouteImport } from './routes/api.payments.c2b.status'
import { Route as ApiPaymentsC2bConfirmationRouteImport } from './routes/api.payments.c2b.confirmation'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MpesaCallbackRoute = MpesaCallbackRouteImport.update({
  id: '/mpesa/callback',
  path: '/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const C2bValidationRoute = C2bValidationRouteImport.update({
  id: '/c2b/validation',
  path: '/c2b/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const C2bConfirmationRoute = C2bConfirmationRouteImport.update({
  id: '/c2b/confirmation',
  path: '/c2b/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSmsAutomationRoute = AppSmsAutomationRouteImport.update({
  id: '/sms-automation',
  path: '/sms-automation',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugRoute = AppDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa/callback',
  path: '/api/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugTestPaymentRoute = ApiDebugTestPaymentRouteImport.update({
  id: '/api/debug/test-payment',
  path: '/api/debug/test-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSimulateC2bRoute = ApiDebugSimulateC2bRouteImport.update({
  id: '/api/debug/simulate-c2b',
  path: '/api/debug/simulate-c2b',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugHealthRoute = ApiDebugHealthRouteImport.update({
  id: '/api/debug/health',
  path: '/api/debug/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugCallbacksRoute = ApiDebugCallbacksRouteImport.update({
  id: '/api/debug/callbacks',
  path: '/api/debug/callbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsC2bValidationRoute =
  ApiPaymentsC2bValidationRouteImport.update({
    id: '/api/payments/c2b/validation',
    path: '/api/payments/c2b/validation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsC2bStatusRoute = ApiPaymentsC2bStatusRouteImport.update({
  id: '/api/payments/c2b/status',
  path: '/api/payments/c2b/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsC2bConfirmationRoute =
  ApiPaymentsC2bConfirmationRouteImport.update({
    id: '/api/payments/c2b/confirmation',
    path: '/api/payments/c2b/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/callback': typeof CallbackRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/customers': typeof AppCustomersRoute
  '/debug': typeof AppDebugRoute
  '/payments': typeof AppPaymentsRoute
  '/settings': typeof AppSettingsRoute
  '/sms-automation': typeof AppSmsAutomationRoute
  '/api/health': typeof ApiHealthRoute
  '/c2b/confirmation': typeof C2bConfirmationRoute
  '/c2b/validation': typeof C2bValidationRoute
  '/mpesa/callback': typeof MpesaCallbackRoute
  '/api/debug/callbacks': typeof ApiDebugCallbacksRoute
  '/api/debug/health': typeof ApiDebugHealthRoute
  '/api/debug/simulate-c2b': typeof ApiDebugSimulateC2bRoute
  '/api/debug/test-payment': typeof ApiDebugTestPaymentRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/payments/c2b/confirmation': typeof ApiPaymentsC2bConfirmationRoute
  '/api/payments/c2b/status': typeof ApiPaymentsC2bStatusRoute
  '/api/payments/c2b/validation': typeof ApiPaymentsC2bValidationRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/customers': typeof AppCustomersRoute
  '/debug': typeof AppDebugRoute
  '/payments': typeof AppPaymentsRoute
  '/settings': typeof AppSettingsRoute
  '/sms-automation': typeof AppSmsAutomationRoute
  '/api/health': typeof ApiHealthRoute
  '/c2b/confirmation': typeof C2bConfirmationRoute
  '/c2b/validation': typeof C2bValidationRoute
  '/mpesa/callback': typeof MpesaCallbackRoute
  '/': typeof AppIndexRoute
  '/api/debug/callbacks': typeof ApiDebugCallbacksRoute
  '/api/debug/health': typeof ApiDebugHealthRoute
  '/api/debug/simulate-c2b': typeof ApiDebugSimulateC2bRoute
  '/api/debug/test-payment': typeof ApiDebugTestPaymentRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/payments/c2b/confirmation': typeof ApiPaymentsC2bConfirmationRoute
  '/api/payments/c2b/status': typeof ApiPaymentsC2bStatusRoute
  '/api/payments/c2b/validation': typeof ApiPaymentsC2bValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/debug': typeof AppDebugRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sms-automation': typeof AppSmsAutomationRoute
  '/api/health': typeof ApiHealthRoute
  '/c2b/confirmation': typeof C2bConfirmationRoute
  '/c2b/validation': typeof C2bValidationRoute
  '/mpesa/callback': typeof MpesaCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/api/debug/callbacks': typeof ApiDebugCallbacksRoute
  '/api/debug/health': typeof ApiDebugHealthRoute
  '/api/debug/simulate-c2b': typeof ApiDebugSimulateC2bRoute
  '/api/debug/test-payment': typeof ApiDebugTestPaymentRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/payments/c2b/confirmation': typeof ApiPaymentsC2bConfirmationRoute
  '/api/payments/c2b/status': typeof ApiPaymentsC2bStatusRoute
  '/api/payments/c2b/validation': typeof ApiPaymentsC2bValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/health'
    | '/login'
    | '/analytics'
    | '/customers'
    | '/debug'
    | '/payments'
    | '/settings'
    | '/sms-automation'
    | '/api/health'
    | '/c2b/confirmation'
    | '/c2b/validation'
    | '/mpesa/callback'
    | '/api/debug/callbacks'
    | '/api/debug/health'
    | '/api/debug/simulate-c2b'
    | '/api/debug/test-payment'
    | '/api/mpesa/callback'
    | '/api/payments/c2b/confirmation'
    | '/api/payments/c2b/status'
    | '/api/payments/c2b/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/health'
    | '/login'
    | '/analytics'
    | '/customers'
    | '/debug'
    | '/payments'
    | '/settings'
    | '/sms-automation'
    | '/api/health'
    | '/c2b/confirmation'
    | '/c2b/validation'
    | '/mpesa/callback'
    | '/'
    | '/api/debug/callbacks'
    | '/api/debug/health'
    | '/api/debug/simulate-c2b'
    | '/api/debug/test-payment'
    | '/api/mpesa/callback'
    | '/api/payments/c2b/confirmation'
    | '/api/payments/c2b/status'
    | '/api/payments/c2b/validation'
  id:
    | '__root__'
    | '/_app'
    | '/callback'
    | '/health'
    | '/login'
    | '/_app/analytics'
    | '/_app/customers'
    | '/_app/debug'
    | '/_app/payments'
    | '/_app/settings'
    | '/_app/sms-automation'
    | '/api/health'
    | '/c2b/confirmation'
    | '/c2b/validation'
    | '/mpesa/callback'
    | '/_app/'
    | '/api/debug/callbacks'
    | '/api/debug/health'
    | '/api/debug/simulate-c2b'
    | '/api/debug/test-payment'
    | '/api/mpesa/callback'
    | '/api/payments/c2b/confirmation'
    | '/api/payments/c2b/status'
    | '/api/payments/c2b/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  C2bConfirmationRoute: typeof C2bConfirmationRoute
  C2bValidationRoute: typeof C2bValidationRoute
  MpesaCallbackRoute: typeof MpesaCallbackRoute
  ApiDebugCallbacksRoute: typeof ApiDebugCallbacksRoute
  ApiDebugHealthRoute: typeof ApiDebugHealthRoute
  ApiDebugSimulateC2bRoute: typeof ApiDebugSimulateC2bRoute
  ApiDebugTestPaymentRoute: typeof ApiDebugTestPaymentRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
  ApiPaymentsC2bConfirmationRoute: typeof ApiPaymentsC2bConfirmationRoute
  ApiPaymentsC2bStatusRoute: typeof ApiPaymentsC2bStatusRoute
  ApiPaymentsC2bValidationRoute: typeof ApiPaymentsC2bValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/mpesa/callback': {
      id: '/mpesa/callback'
      path: '/mpesa/callback'
      fullPath: '/mpesa/callback'
      preLoaderRoute: typeof MpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c2b/validation': {
      id: '/c2b/validation'
      path: '/c2b/validation'
      fullPath: '/c2b/validation'
      preLoaderRoute: typeof C2bValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c2b/confirmation': {
      id: '/c2b/confirmation'
      path: '/c2b/confirmation'
      fullPath: '/c2b/confirmation'
      preLoaderRoute: typeof C2bConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sms-automation': {
      id: '/_app/sms-automation'
      path: '/sms-automation'
      fullPath: '/sms-automation'
      preLoaderRoute: typeof AppSmsAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug': {
      id: '/_app/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AppDebugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/mpesa/callback': {
      id: '/api/mpesa/callback'
      path: '/api/mpesa/callback'
      fullPath: '/api/mpesa/callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/test-payment': {
      id: '/api/debug/test-payment'
      path: '/api/debug/test-payment'
      fullPath: '/api/debug/test-payment'
      preLoaderRoute: typeof ApiDebugTestPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/simulate-c2b': {
      id: '/api/debug/simulate-c2b'
      path: '/api/debug/simulate-c2b'
      fullPath: '/api/debug/simulate-c2b'
      preLoaderRoute: typeof ApiDebugSimulateC2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/health': {
      id: '/api/debug/health'
      path: '/api/debug/health'
      fullPath: '/api/debug/health'
      preLoaderRoute: typeof ApiDebugHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/callbacks': {
      id: '/api/debug/callbacks'
      path: '/api/debug/callbacks'
      fullPath: '/api/debug/callbacks'
      preLoaderRoute: typeof ApiDebugCallbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/c2b/validation': {
      id: '/api/payments/c2b/validation'
      path: '/api/payments/c2b/validation'
      fullPath: '/api/payments/c2b/validation'
      preLoaderRoute: typeof ApiPaymentsC2bValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/c2b/status': {
      id: '/api/payments/c2b/status'
      path: '/api/payments/c2b/status'
      fullPath: '/api/payments/c2b/status'
      preLoaderRoute: typeof ApiPaymentsC2bStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/c2b/confirmation': {
      id: '/api/payments/c2b/confirmation'
      path: '/api/payments/c2b/confirmation'
      fullPath: '/api/payments/c2b/confirmation'
      preLoaderRoute: typeof ApiPaymentsC2bConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDebugRoute: typeof AppDebugRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmsAutomationRoute: typeof AppSmsAutomationRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDebugRoute: AppDebugRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmsAutomationRoute: AppSmsAutomationRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  C2bConfirmationRoute: C2bConfirmationRoute,
  C2bValidationRoute: C2bValidationRoute,
  MpesaCallbackRoute: MpesaCallbackRoute,
  ApiDebugCallbacksRoute: ApiDebugCallbacksRoute,
  ApiDebugHealthRoute: ApiDebugHealthRoute,
  ApiDebugSimulateC2bRoute: ApiDebugSimulateC2bRoute,
  ApiDebugTestPaymentRoute: ApiDebugTestPaymentRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
  ApiPaymentsC2bConfirmationRoute: ApiPaymentsC2bConfirmationRoute,
  ApiPaymentsC2bStatusRoute: ApiPaymentsC2bStatusRoute,
  ApiPaymentsC2bValidationRoute: ApiPaymentsC2bValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
